## Array Types and Conversions between Types

**Numpy Supports a greater Variety of Data Types in Comparison to Python**

### Primitive Types

<table style="width:50%; font-size: 17px; background-color: lightblue; color: black
              ; border-spacing: 5px; border: 2px solid black">
    <tr>
    <th>Numpy Type</th>
    <th>C Type</th>
    </tr>
    <tr>
        <td>np.bool</td>
        <td>bool</td>
    </tr>
        <tr>
        <td>np.byte</td>
        <td>Signed Char</td>
    </tr>
        <tr>
        <td>np.ubyte</td>
        <td>Unsigned Char</td>
    </tr>
        <tr>
        <td>np.short</td>
        <td>short</td>
    </tr>
        <tr>
        <td>np.ushort</td>
        <td>unsigned short</td>
    </tr>
        <tr>
        <td>np.intc</td>
        <td>int</td>
    </tr>
        <tr>
        <td>np.uintc</td>
        <td>unsigned int</td>
    </tr>
        <tr>
        <td>np.int_</td>
        <td>long</td>
    </tr>
        <tr>
        <td>np.uint</td>
        <td>unsigned long</td>
    </tr>
        <tr>
        <td>np.longlong</td>
        <td>long long</td>
    </tr>
    <tr>
        <td>np.ulonglong</td>
        <td>unsigned long long</td>
    </tr>
        <tr>
        <td>np.half / np.float16</td>
        <td>Half Precision Float</td>
    </tr>
        <tr>
        <td>np.single</td>
        <td>float</td>
    </tr>
        <tr>
        <td>np.double</td>
        <td>double</td>
    </tr>
        <tr>
        <td>np.longdouble</td>
        <td>long double</td>
    </tr>
        <tr>
        <td>np.csingle</td>
        <td>float complex</td>
    </tr>
      <tr>
        <td>np.cdouble</td>
        <td>double complex</td>
    </tr>
   <tr>
        <td>np.clongdouble</td>
        <td>long double complex</td>
    </tr>
</table>
  

### Fixed Size Aliases

<table style="width:50%; font-size: 17px; background-color: lightblue; color: black
              ; border-spacing: 5px; border: 2px solid black">
    <tr>
    <th>Numpy Type</th>
    <th>C Type</th>
    </tr>
    <tr>
        <td>np.int8</td>
        <td>int8_t</td>
    </tr>
        <tr>
        <td>np.int16</td>
        <td>int16_t</td>
    </tr>
        <tr>
        <td>np.int32</td>
        <td>int32_t</td>
    </tr>
        <tr>
        <td>np.int64</td>
        <td>int64_t</td>
    </tr>
        <tr>
        <td>np.uint8</td>
        <td>uint8_t</td>
    </tr>
        <tr>
        <td>np.uint16</td>
        <td>uint16_t</td>
    </tr>
        <tr>
        <td>np.uint32</td>
        <td>uint32_t</td>
    </tr>
        <tr>
        <td>np.uint64</td>
        <td>uint64_t</td>
    </tr>
        <tr>
        <td>np.intp</td>
        <td>intptr_t</td>
    </tr>
        <tr>
        <td>np.uintp</td>
        <td>uintptr_t</td>
    </tr>
    <tr>
        <td>float32</td>
        <td>float</td>
    </tr>
        <tr>
        <td>float64</td>
        <td>double</td>
    </tr>
        <tr>
        <td>complex64</td>
        <td>complex</td>
    </tr>
        <tr>
        <td>complex128</td>
        <td>complex</td>
    </tr>
     
</table>
  

In [2]:
import numpy as np

In [3]:
x = np.float32(1.0)
print(x)

1.0


In [4]:
x = np.float64(946464646464646464646464646464466.333131313113)
print(x)

9.464646464646464e+32


In [5]:
x = np.int_([1,2,4])
print(x)

[1 2 4]


In [7]:
x = np.arange(3, dtype=np.uint8)
print(x)

[0 1 2]


In [6]:
x = np.arange(2, 10, 2)
x

array([2, 4, 6, 8])

In [8]:
x = np.array([1, 2, 3], dtype='f')
print(x)

[1. 2. 3.]


In [10]:
x = np.int8(34)
print(x)

34
