## There are 5 general mechanisms for creating arrays:

* Conversion from other Python structures (e.g., lists, tuples)
* Intrinsic numpy array creation objects (e.g., arange, ones, zeros, etc.)
* Reading arrays from disk, either from standard or custom formats
* Creating arrays from raw bytes through the use of strings or buffers
* Use of special library functions (e.g., random)

## Instrinsic Array Creation

In [3]:
import numpy as np

In [4]:
np.zeros((7, 8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
np.ones((5, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [5]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
np.arange(3.5, 9.8, 0.2)

array([3.5, 3.7, 3.9, 4.1, 4.3, 4.5, 4.7, 4.9, 5.1, 5.3, 5.5, 5.7, 5.9,
       6.1, 6.3, 6.5, 6.7, 6.9, 7.1, 7.3, 7.5, 7.7, 7.9, 8.1, 8.3, 8.5,
       8.7, 8.9, 9.1, 9.3, 9.5, 9.7])

In [8]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [9]:
np.arange(2, 10, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. , 6.2, 6.4, 6.6, 6.8, 7. ,
       7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6, 8.8, 9. , 9.2, 9.4, 9.6,
       9.8])

In [21]:
np.linspace(5, 10, 6)

array([ 5.,  6.,  7.,  8.,  9., 10.])

In [13]:
np.linspace(1, 10, 20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [4]:
import numpy as np
np.indices((2, 3, 1))

array([[[[0],
         [0],
         [0]],

        [[1],
         [1],
         [1]]],


       [[[0],
         [1],
         [2]],

        [[0],
         [1],
         [2]]],


       [[[0],
         [0],
         [0]],

        [[0],
         [0],
         [0]]]])

In [22]:
x = np.array([1, 2, 3])
print(x)

[1 2 3]


In [25]:
x = np.array([[0, 0],[1, 1]])
print(x)

[[0 0]
 [1 1]]
