## Built in Functions in Numpy

**We will cover some of the most useful built in functions available in numpy**

For initializing arrays.

Apart from usual arrays, we can also create arrays with special patterns

The following ways are commonly used:
    
* ```np.ones()```: Create array of 1s
* ```np.zeros()```: Create array of 0s
* ```np.random.random()```: Create array of random numbers
* ```np.arange()```: Create array with increments of a fixed step size
* ```np.linspace()```: Create array of fixed length

In [3]:
import numpy as np

In [4]:
# lets check the documentation of np.ones()

help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C')
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    
    Returns
    -------
    out : ndarray
        Array of ones with the given shape, dtype, and order.
    
    See Also
    --------
    ones_like : Return an array of ones with shape and type of input.
    empty : Return a new uninitialized array.
    zeros : Return a new array setting values to zero.
    full : Return a new array of given shape filled with value.
    
    
    Examples
    --------
   

**zeros**

In [10]:
np.zeros(4)

array([0., 0., 0., 0.])

In [12]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
np.zeros((2, 3), dtype = 'int')

array([[0, 0, 0],
       [0, 0, 0]])

**random**

In [21]:
np.random.random(3)

array([0.2970947 , 0.56657206, 0.47611966])

In [24]:
np.random.random(11)

array([0.00613516, 0.7985658 , 0.21666784, 0.59858   , 0.74860301,
       0.13668978, 0.29025155, 0.21530567, 0.86685888, 0.88151767,
       0.93046111])

**arange**

In [27]:
np.arange(2, 50)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35,
       36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [28]:
np.arange(2, 200, 10)

array([  2,  12,  22,  32,  42,  52,  62,  72,  82,  92, 102, 112, 122,
       132, 142, 152, 162, 172, 182, 192])

**linspace**

In [31]:
np.linspace(1, 10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [32]:
np.linspace(2, 7, 10)

array([2.        , 2.55555556, 3.11111111, 3.66666667, 4.22222222,
       4.77777778, 5.33333333, 5.88888889, 6.44444444, 7.        ])

Apart from the methods mentioned above, there are a few more NumPy functions that you can use to create special NumPy arrays:

-  `np.full()`: Create a constant array of any number ‘n’
-  `np.tile()`: Create a new array by repeating an existing array for a particular number of times
-  `np.eye()`: Create an identity matrix of any dimension
-  `np.random.randint()`: Create a random array of integers within a particular range

**full**

In [2]:
import numpy as np
np.full((2,5), 6)

array([[6, 6, 6, 6, 6],
       [6, 6, 6, 6, 6]])

In [36]:
np.full(5, 9)

array([9, 9, 9, 9, 9])

**tile**

In [4]:
np.tile([0, 1], 5)

array([0, 1, 0, 1, 0, 1, 0, 1, 0, 1])

In [38]:
np.tile([0, 1], [3, 4])

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [0, 1, 0, 1, 0, 1, 0, 1]])

**eye**

In [33]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**randint**

In [43]:
np.random.randint(1, 100)

89

In [45]:
np.random.randint(30)

15

In [46]:
np.random.randint(-40, 40)

18

### Inspect the Structure and Content of Arrays

It is helpful to inspect the structure of numpy arrays, especially while working with large arrays. Some attributes of numpy arrays are:
* ```shape```: Shape of array (n x m)
* ```dtype```: data type (int, float etc.)
* ```ndim```: Number of dimensions (or axes)
* ```itemsize```: Memory used by each array elememnt in bytes


Let's say you are working with a moderately large array of size 1000 x 300. First, you would want to wrap your head around the basic shape and size of the array. 

In [48]:
a = np.array([2, 3, 45, 6])
print(a)

[ 2  3 45  6]


In [49]:
a.shape

(4,)

In [50]:
a.dtype

dtype('int32')

In [51]:
a.ndim

1

In [52]:
a.itemsize

4