# Operations on NumPy Arrays

The learning objectives of this section are:

* Manipulate arrays
    * Reshape arrays
    * Stack arrays
* Perform operations on arrays
    * Perform basic mathematical operations
    * Apply built-in functions 
    * Apply your own functions 
    * Apply basic linear algebra operations 


In [6]:
import numpy as np

x= np.zeros((2, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


### Manipulating Arrays

Let's look at some ways to manipulate arrays, i.e. changing the shape, combining and splitting arrays, etc.   

#### Reshaping Arrays

Reshaping is done using the ```reshape()``` function.

In [2]:
import numpy as np


In [4]:
# lets take an array a and take 12 elements inside it

a = np.arange(0, 12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [8]:
# lets try to resize this array

print('Array with 3 Rows and 4 Columns')
b = a.reshape(3, 4)
print(b,'\n')

print('Array with 4 Rows and 3 Columns')
c = a.reshape(4, 3)
print(c, '\n')

print('Array with 6 Rows and 2 Columns')
d = a.reshape(6, 2)
print(d, '\n')

print('Array with 2 Rows and 6 Columns')
e = a.reshape(2, 6)
print(e, '\n')


Array with 3 Rows and 4 Columns
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

Array with 4 Rows and 3 Columns
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

Array with 6 Rows and 2 Columns
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

Array with 2 Rows and 6 Columns
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]] 



### -1 means "whatever dimension is needed" 

In [9]:
# If you specify -1 as a dimension, the dimensions are automatically calculated

x = a.reshape(4, -1)
y = a.reshape(3, -1)
z = a.reshape(6, -1)
q = a.reshape(2, -1)

print(x, '\n')
print(y, '\n')
print(z, '\n')
print(a, '\n')

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[ 0  1  2  3  4  5  6  7  8  9 10 11] 



### Transposing an Array

In [3]:
import numpy as np
x = np.full((2, 6), 4)
x.T

array([[4, 4],
       [4, 4],
       [4, 4],
       [4, 4],
       [4, 4],
       [4, 4]])

In [14]:
# lets make an array and transpose the array

# lets take an array
array = np.array([[3, 4, 4],[7, 7,8]])

print('Before Transposition of Array b')
print(array)

# lets transpose the array
transpose = array.T

print('After Transposition of Array a')
print(transpose)

Before Transposition of Array b
[[3 4 4]
 [7 7 8]]
After Transposition of Array a
[[3 7]
 [4 7]
 [4 8]]


### Stacking of Arrays

#### Stacking: ```np.hstack()``` and ```n.vstack()```

Stacking is done using the ```np.hstack()``` and ```np.vstack()``` methods. For horizontal stacking, the number of rows should be the same, while for vertical stacking, the number of columns should be the same.

In [16]:
# lets create two arrays for performing the operation of vertical stacking

# for vertical stacking the number of columns must be same
arr1 = np.arange(28).reshape(7, 4)
arr2 = np.arange(20).reshape(5, 4)

print('First Array')
print(arr1, '\n')
print('Second Array')
print(arr2)

First Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]] 

Second Array
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


### vstack

In [17]:
# Note that np.vstack(a, b) throws an error - you need to pass the arrays as a list

np.vstack((arr1, arr2))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

### hstack

In [18]:
# lets create two arrays for performing the operation of vertical stacking

# for horizontal stakcing we must have same numbers of rows
arr1 = np.arange(21).reshape(3, 7)
arr2 = np.arange(6).reshape(3, 2)

print('First Array')
print(arr1, '\n')
print('Second Array')
print(arr2)

First Array
[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]] 

Second Array
[[0 1]
 [2 3]
 [4 5]]


In [19]:
# Note that np.hstack(a, b) throws an error - you need to pass the arrays as a list

np.hstack((arr1, arr2))

array([[ 0,  1,  2,  3,  4,  5,  6,  0,  1],
       [ 7,  8,  9, 10, 11, 12, 13,  2,  3],
       [14, 15, 16, 17, 18, 19, 20,  4,  5]])

### Basic Mathematical Operations

#### 1. Single Array Operations

In [10]:
a = np.array([2, 3, 5, 6, 7, 8])

sin = np.sin(a)
cos = np.cos(a)
tan = np.tan(a)
log = np.log(a)
exp = np.exp(a)
sqrt = np.sqrt(a)
sqrt

array([1.41421356, 1.73205081, 2.23606798, 2.44948974, 2.64575131,
       2.82842712])

In [12]:
x = [2, 3, 4, 5, 6]
z = [1/a for a in x]
z

[0.5, 0.3333333333333333, 0.25, 0.2, 0.16666666666666666]

In [28]:
# lets create an array, where we will perform our operations

array = np.arange(10)

# sin function
print('sin of array a')
sin = np.sin(array)
print(sin, '\n')

# cos function
print('cos of array a')
cos = np.cos(array)
print(cos, '\n')

# tan function
print('tan of array a')
tan = np.tan(array)
print(tan, '\n')

# log function
print('log of array a')
log = np.log(array)
print(log, '\n')

# exp function
print('exp of array a')
exp = np.exp(array)
print(exp, '\n')

# sqrt function
print('sqrt of array a')
exp = np.sqrt(array)
print(exp, '\n')


sin of array a
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849] 

cos of array a
[ 1.          0.54030231 -0.41614684 -0.9899925  -0.65364362  0.28366219
  0.96017029  0.75390225 -0.14550003 -0.91113026] 

tan of array a
[ 0.          1.55740772 -2.18503986 -0.14254654  1.15782128 -3.38051501
 -0.29100619  0.87144798 -6.79971146 -0.45231566] 

log of array a
[      -inf 0.         0.69314718 1.09861229 1.38629436 1.60943791
 1.79175947 1.94591015 2.07944154 2.19722458] 

exp of array a
[1.00000000e+00 2.71828183e+00 7.38905610e+00 2.00855369e+01
 5.45981500e+01 1.48413159e+02 4.03428793e+02 1.09663316e+03
 2.98095799e+03 8.10308393e+03] 

sqrt of array a
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ] 



c:\users\roshan\appdata\local\programs\python\python36\lib\site-packages\ipykernel_launcher.py:22: RuntimeWarning: divide by zero encountered in log


#### 2. Double Array Operations

* Element Wise Operations

In [38]:
# lets take two arrays on which we will perform the operations

a = np.array([7, 5, 2, 3])
b = np.array([5, 8, 3, 5])

# mathematical operations

print('Sum Operation between arrays a and b')
add = np.add(a, b)
print(add, '\n')

print('Subtract Operation between arrays a and b')
subtract = np.subtract(a, b)
print(subtract, '\n')

print('Multiply Operation between arrays a and b')
multiply = np.multiply(a, b)
print(multiply, '\n')

print('Divide Operation between arrays a and b')
div = np.divide(a, b)
print(div, '\n')

print('power Operation between arrays a and b')
power = np.power(a, b)
print(power, '\n')

print('Remainder Operation between arrays a and b')
rem = np.remainder(a, b)
print(rem, '\n')

print('Modulus Operation between arrays a and b')
mod = np.mod(a, b)
print(mod, '\n')

Sum Operation between arrays a and b
[12 13  5  8] 

Subtract Operation between arrays a and b
[ 2 -3 -1 -2] 

Multiply Operation between arrays a and b
[35 40  6 15] 

Divide Operation between arrays a and b
[1.4        0.625      0.66666667 0.6       ] 

power Operation between arrays a and b
[ 16807 390625      8    243] 

Remainder Operation between arrays a and b
[2 5 2 3] 

Modulus Operation between arrays a and b
[2 5 2 3] 



### Applying Built in Functions

* While applying Built in functions, we have two choices, 
  * The First Choice is to loop through the array, i.e., using for loop
  * The Second Choice is to use vectorize function using numpy

**First Method: Non Numpy Method, Using for Loop or list comprehensions**

In [46]:
# lets take an array

a = np.arange(20)
print("Array a, before operation")
print(a, '\n')

b = [x*x+1 for x in a]
print("Array a, after operation")
print(b)

Array a, before operation
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

Array a, after operation
[1, 2, 5, 10, 17, 26, 37, 50, 65, 82, 101, 122, 145, 170, 197, 226, 257, 290, 325, 362]


**Second Method: Numpy Method, Using a Vectorize function**

In [43]:
# lets take an array

a = np.arange(20)
print("Array a, before operation")
print(a, '\n')

function = np.vectorize(lambda x: x*x+1)

# lets apply this function to the array a
print("Array a, after Operation")
print(function(a))

Array a, before operation
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19] 

Array a, after Operation
[  1   2   5  10  17  26  37  50  65  82 101 122 145 170 197 226 257 290
 325 362]


In [68]:
# let's take some more examples on 2d arrays

a = np.linspace(1, 100, 10).reshape(2, 5)
print("Array a, efore operation")
print(a, '\n')

function = np.vectorize(lambda x: (x**3+67-x)/2**x )

# lets apply the function to the 2d array a
print("Array a, after Operation")
print(function(a))

Array a, efore operation
[[  1.  12.  23.  34.  45.]
 [ 56.  67.  78.  89. 100.]] 

Array a, after Operation
[[3.35000000e+01 4.35302734e-01 1.45566463e-03 2.28971476e-06
  2.59055355e-09]
 [2.43731424e-12 2.03804936e-15 1.57012446e-18 1.13890330e-21
  7.88834873e-25]]


### Linear Algebra

NumPy provides the ```np.linalg``` package to apply common linear algebra operations, such as:
* ```np.linalg.inv```: Inverse of a matrix
* ```np.linalg.det```: Determinant of a matrix
* ```np.linalg.eig```: Eigenvalues and eigenvectors of a matrix
    
Also, you can multiple matrices using ```np.dot(a, b)```. 

In [88]:
# lets read the documentation

help(np.linalg)

Help on package numpy.linalg in numpy:

NAME
    numpy.linalg

DESCRIPTION
    ``numpy.linalg``
    
    The NumPy linear algebra functions rely on BLAS and LAPACK to provide efficient
    low level implementations of standard linear algebra algorithms. Those
    libraries may be provided by NumPy itself using C versions of a subset of their
    reference implementations but, when possible, highly optimized libraries that
    take advantage of specialized processor functionality are preferred. Examples
    of such libraries are OpenBLAS, MKL (TM), and ATLAS. Because those libraries
    are multithreaded and processor dependent, environmental variables and external
    packages such as threadpoolctl may be needed to control the number of threads
    or specify the processor architecture.
    
    - OpenBLAS: https://www.openblas.net/
    - threadpoolctl: https://github.com/joblib/threadpoolctl
    
    Please note that the most-used linear algebra functions in NumPy are present in
    t

In [93]:
# Creating arrays
p = np.arange(1, 10).reshape(3, 3)
q= np.arange(1, 13).reshape(3, 4)
print(p)
print(q)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [102]:
# Inverse
np.linalg.det(a)

0.0

In [104]:
np.linalg.eig(a)

(array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]),
 array([[-0.23197069, -0.78583024,  0.40824829],
        [-0.52532209, -0.08675134, -0.81649658],
        [-0.8186735 ,  0.61232756,  0.40824829]]))

In [106]:
np.dot(a, b)

array([[ 38,  44,  50,  56],
       [ 83,  98, 113, 128],
       [128, 152, 176, 200]])

In [16]:
a = np.array([[2, 3, 4, 5], [2, 5, 6, ]])
a

array([list([2, 3, 4, 5]), list([2, 5, 6])], dtype=object)

In [18]:
a = np.array([[2, 3, 4, 5], [2, 5, 6, 6 ]])
a

array([[2, 3, 4, 5],
       [2, 5, 6, 6]])